
export enum ModuleType {
  DASHBOARD = 'DASHBOARD',
  PRE_PRODUCTION = 'PRE_PRODUCTION',
  PRODUCTION = 'PRODUCTION',
  POST_PRODUCTION = 'POST_PRODUCTION',
  AIGC_VIDEO = 'AIGC_VIDEO',
  ARCHITECTURE = 'ARCHITECTURE',
}

export interface User {
  name: string;
  role: 'student' | 'teacher';
  avatar?: string;
}

export interface DashboardStats {
  studentEngagement: number; // Calculated 0-100 based on activity
  agentInterventions: number; // Total logs count
  assetsCreated: number; // Scripts + Shots + Videos
  systemLoad: number; // Mock load based on current processing status
}

export interface LogEntry {
  id: string;
  timestamp: string;
  source: 'Teacher Agent' | 'Student Agent' | 'Assistant Agent' | 'Director Agent' | 'Cinematography Agent' | 'Editor Agent' | 'System' | 'Veo Model';
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
}

export interface ScriptProject {
  title: string;
  genre: string;
  logline: string;
  structureAnalysis: string; 
  characterNotes: string;
  scenes: string[]; // List of key scenes generated by AI
}

export interface ShotPlan {
  id: number;
  shotType: string;
  angle: string;
  movement: string;
  lighting: string;
  description: string;
  technicalReasoning: string; // "Why this shot?"
  visualPrompt: string; // Prompt for image generation
  storyboardUrl?: string; // Generated image URL
}

export interface VideoAdjustments {
  contrast: number;   // 1.0 is normal
  brightness: number; // 1.0 is normal
  saturation: number; // 1.0 is normal
  warmth: number;     // 0 is normal (sepia/filter simulation)
}

export interface EditingFeedback {
  id: string;
  timecode: string;
  suggestion: string;
  category: 'Rhythm' | 'Continuity' | 'Audio' | 'Color' | 'Composition' | 'Focus' | 'Lighting' | 'Plan Compliance';
  severity: 'low' | 'medium' | 'high';
  recommendedAdjustments?: VideoAdjustments; // AI suggested color grading
}

export type VideoGenerationMode = 'VEO' | 'ANIMATIC';

export interface VideoGenerationState {
  userPrompt: string;
  refinedPrompt: string;
  mode: VideoGenerationMode;
  videoUrl: string | null;
  keyframes: string[]; // For Animatic mode (list of image URLs)
  status: AgentState;
}

export enum AgentState {
  IDLE = 'IDLE',
  ANALYZING = 'ANALYZING',
  GENERATING = 'GENERATING',
  COLLABORATING = 'COLLABORATING',
  PROCESSING = 'PROCESSING', // For video rendering
}

export interface Task {
  id: string;
  title: string;
  description: string;
  targetModule: ModuleType;
  deadline: string;
  status: 'active' | 'completed' | 'archived';
  timestamp: string;
}
